version: "3"
volumes:
  pg-db-data:
services:
  postgres:
    image: 'postgres:11.2-alpine'
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pg-db-data:/var/lib/postgresql/data
  adminer:
    image: 'adminer:4.7.1-standalone'
    restart: always
    ports:
      - 9090:8080
  symfony:
    build:
      dockerfile: Dockerfile.dev
      context: ./symfony
    ports:
      - 8080:80
    volumes:
      - /var/www/vendor #exlude mounting of vendor / mount the vendor to nothing
      - /var/www/docker #same for the docker directory (because theres ist the startup script) -> needs chmod a+x and be on the server
      - ./symfony:/var/www # mount the rest of the symfony files inside /var/www
#  router:
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./router
