version: "3"
volumes:
  pg-db-data:
services:
  postgres:
    image: 'postgres:11.2-alpine'
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - pg-db-data:/var/lib/postgresql/data
  adminer:
    image: 'adminer:4.7.1-standalone'
    restart: always
    ports:
      - 9090:8080
  symfony:
    build:
      dockerfile: Dockerfile
      context: ./symfony
  router:
    build:
      dockerfile: Dockerfile.dev
      context: ./router
# only necessary if i would use upstream directive see nginx/nginx/default.conf -> then the order must be fix otherwise nginx wouldnt start anymore (if nginx is earlier than the upstreams)
#    depends_on: 
#      - symfony
    ports:
      - 8080:80
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
