framework:
    workflows: 
        enrollment:
            type: "workflow"
            marking_store:
                type: 'multiple_state' # or 'single_state'
                arguments: 
                    - 'status'
            supports:
                - App\Entity\Enrollment
            initial_place: enrolled
            places:
                - enrolled
                - waiting for email confirmation
                - email confirmed
                - confirmed
            transitions:
                waiting for confirmations:
                    from: enrolled
                    to: 
                        - waiting for email confirmation
                confirm email:
                    from:  waiting for email confirmation
                    to: confirmed
                confirm enrollment direct:
                    from: enrolled
                    to: confirmed